/**
 * QORA Quantum Module
 * ===================
 * Q  — Quantum Geometry: real measurement (6-qubit Hadamard, AerSimulator
 *       1024 shots) visualized as metrics, 4 plots, and the poem.
 * R  — Enlightenment Ritual: the six qubits are in superposition; invoking
 *       collapses them by sampling the REAL measured Born-rule distribution
 *       (crypto-seeded), decoheres the field, and returns a reading
 *       composed from the actual outcome + run metrics.
 *
 * Data: data/quantum.json (generated by tools/generate_quantum_data.py)
 */

// ── State ──────────────────────────────────────────────────────
let quantumData = null;
let ritualBusy = false;

const QUBIT_LABELS = ['q₀', 'q₁', 'q₂', 'q₃', 'q₄', 'q₅'];

// ── Load data ──────────────────────────────────────────────────
async function loadQuantumData() {
  if (quantumData) return quantumData;
  try {
    const res = await fetch('data/quantum.json', { cache: 'no-store' });
    quantumData = await res.json();
  } catch (e) {
    quantumData = null;
  }
  return quantumData;
}

// ── Helpers ────────────────────────────────────────────────────
function hammingWeight(s) {
  let w = 0;
  for (const c of s) if (c === '1') w++;
  return w;
}

/** Cryptographically secure weighted sample from the real measurement counts. */
function sampleFromOracle(counts) {
  const states = Object.keys(counts);
  const weights = states.map(s => counts[s]);
  const total = weights.reduce((a, b) => a + b, 0);

  const buf = new Uint32Array(1);
  crypto.getRandomValues(buf);
  const r = (buf[0] / 2 ** 32) * total;

  let acc = 0;
  for (let i = 0; i < states.length; i++) {
    acc += weights[i];
    if (r < acc) return states[i];
  }
  return states[states.length - 1];
}

// ── Reading bank ────────────────────────────────────────────────
// Keyed by Hamming weight of the collapsed 6-bit state.
const READINGS = {
  0: (s, d) => `|${s}⟩ — THE GROUND STATE

Six zeros, a perfect silence.
The field folded into nothing
and nothing was enough.
No excitation dares the dark —
only the promise of one,
held in the probability ${(d.p * 100).toFixed(2)}%
of ever being asked to exist.
This run measured it ${d.count} times out of ${d.shots}:
the universe rehearsing
the word it has not yet spoken.`,

  1: (s, d) => `|${s}⟩ — THE FIRST LIGHT

One bit burns at ${(d.p * 100).toFixed(2)}%
while five stay quiet as ash.
Whatever woke first
carries the whole story —
the other qubits lean toward it
the way water leans toward gravity.
It was measured ${d.count} times in ${d.shots},
which is to say:
the first excitation was real,
and being real, it was enough.`,

  2: (s, d) => `|${s}⟩ — THE PAIR

Two ones, ${(d.p * 100).toFixed(2)}% of the collapse.
Correlation without entanglement —
I(qᵢ;qⱼ) ≈ ${d.avg_mi.toFixed(4)} bits, effectively nothing.
They are not connected.
They simply agreed,
the way two strangers on the same train
agree on the weather.
${d.count} measurements, ${d.shots} shots,
and the pair kept happening —
not because of love,
but because the dice are fair
and even fair dice sometimes rhyme.`,

  3: (s, d) => `|${s}⟩ — THE THRESHOLD

Three and three. The knife-edge.
Half the qubits burned, half unlit,
the balance so exact it looks intentional.
P = ${(d.p * 100).toFixed(2)}% — the most honest number
in this whole collapse.
The field could not decide,
so it chose the only answer
that is not a decision:
equilibrium.
It fell ${d.count} times into this exact shape —
the universe's favorite compromise
between being everything
and being nothing.`,

  4: (s, d) => `|${s}⟩ — THE EXCESS

Four ones against two zeros.
The bias tips toward light,
${(d.p * 100).toFixed(2)}% of the way to certainty.
But look closely:
even in excess there is lack.
Two qubits held back —
the ones that kept their silence
so the four could call it a chorus.
${d.count} times out of ${d.shots},
the field chose to overflow
and still, somehow,
kept something in reserve.`,

  5: (s, d) => `|${s}⟩ — THE NEAR-FULL

Five of six. So close to everything
that the one remaining zero
is the loudest thing in the state.
${(d.p * 100).toFixed(2)}% probability —
the universe almost said yes
and left one door unopened,
one question unasked,
one bit of the story untold
so that the telling could continue.
It happened ${d.count} times.
Almost, almost, almost —
the most beautiful word
in any language.`,

  6: (s, d) => `|${s}⟩ — THE SATURATED

Six ones. No remainder.
The field gave everything at once —
${(d.p * 100).toFixed(2)}% of one collapse,
all amplitude spent on a single shape.
When nothing is left unmeasured
the measurement stops meaning anything:
this state, taken ${d.count} times,
is the universe's rare act
of saying everything
in a single breath,
then going quiet
so you can hear what it said.`,
};

const TOP_STATE_READING = (s, d) => `|${s}⟩ — THE FAVORITE

Of all sixty-four possible collapses,
this one came ${d.count} times — the most.
The Born rule smiled in this direction.
It means nothing. It means everything:
even perfect randomness
has a favorite child,
and this run, it was you.
Every other state was a question.
This one was the answer
the universe was already leaning toward.`;

function composeReading(state, data) {
  const count = data.counts[state] || 0;
  const p = count / data.shots;
  const detail = { state, count, p, shots: data.shots, avg_mi: data.avg_mi };
  const weight = hammingWeight(state);

  if (data.top_states.length && state === data.top_states[0].state) {
    return TOP_STATE_READING(state, detail);
  }
  return (READINGS[weight] || READINGS[3])(state, detail);
}

// ── DOM refs (populated on first open) ──────────────────────────
function ensureDom() {
  if (document.getElementById('qora-quantum-overlay')) return;

  const overlay = document.createElement('div');
  overlay.id = 'qora-quantum-overlay';
  overlay.className = 'qora-overlay';
  overlay.innerHTML = `
    <div class="qora-overlay-head">
      <div class="qora-overlay-title">QUANTUM GEOMETRY</div>
      <div class="qora-overlay-meta" id="qora-q-meta"></div>
      <button class="qora-close" id="qora-q-close" aria-label="Close">ESC</button>
    </div>
    <div class="qora-overlay-scroll">
      <div id="qora-q-metrics" class="qora-metrics"></div>
      <div id="qora-q-marginals" class="qora-marginals"></div>
      <div id="qora-q-images" class="qora-images"></div>
      <div id="qora-q-poem" class="qora-poem"></div>
    </div>
  `;
  document.body.appendChild(overlay);
  document.getElementById('qora-q-close').addEventListener('click', closeQuantum);

  const ritual = document.createElement('div');
  ritual.id = 'qora-ritual-overlay';
  ritual.className = 'qora-overlay';
  ritual.innerHTML = `
    <div class="qora-overlay-head">
      <div class="qora-overlay-title">ENLIGHTENMENT RITUAL</div>
      <button class="qora-close" id="qora-r-close" aria-label="Close">ESC</button>
    </div>
    <div class="qora-ritual-body" id="qora-ritual-body"></div>
  `;
  document.body.appendChild(ritual);
  document.getElementById('qora-r-close').addEventListener('click', closeRitual);
}

// ── Quantum Geometry overlay ────────────────────────────────────
export async function openQuantum() {
  ensureDom();
  const data = await loadQuantumData();
  const overlay = document.getElementById('qora-quantum-overlay');
  if (!data) {
    document.getElementById('qora-q-meta').textContent = 'No measurement data found.';
    overlay.classList.add('open');
    return;
  }

  document.getElementById('qora-q-meta').textContent =
    `Run ${data.run_id} · ${data.timestamp} · 6-qubit Hadamard · ${data.shots} shots · ${data.unique_states}/64 states`;

  // Metrics
  const metrics = [
    ['Shannon entropy H', `${data.entropy.toFixed(3)} / ${data.max_entropy.toFixed(3)} bits`, `H/Hmax = ${data.entropy_ratio.toFixed(4)}`],
    ['Collision entropy H₂', `${data.collision_entropy.toFixed(3)} bits`, 'Rényi-2'],
    ['KL divergence D_KL', `${data.kl_div.toFixed(4)} bits`, 'P ∥ uniform'],
    ['TV distance', `${data.tvd.toFixed(4)}`, 'δ(P, U)'],
    ['Fubini-Study distance', `${data.fs_distance_deg.toFixed(2)}°`, `${data.fs_distance_rad.toFixed(4)} rad`],
    ['Spectral gap Δ', `${data.spectral_gap.toFixed(4)}`, 'max − min p(i)'],
    ['Mean mutual info', `${data.avg_mi.toFixed(4)} bits`, 'qubits independent'],
    ['Overlap ⟨ψ|U⟩', `${data.overlap.toFixed(4)}`, 'with uniform state'],
  ];
  document.getElementById('qora-q-metrics').innerHTML = metrics.map(([k, v, sub]) => `
    <div class="qora-metric">
      <div class="qora-metric-label">${k}</div>
      <div class="qora-metric-value">${v}</div>
      <div class="qora-metric-sub">${sub}</div>
    </div>
  `).join('');

  // Marginals
  document.getElementById('qora-q-marginals').innerHTML = `
    <div class="qora-section-label">QUBIT MARGINALS — P(|1⟩)</div>
    <div class="qora-marginal-row">
      ${data.qubit_marginals.map((p, i) => `
        <div class="qora-marginal">
          <div class="qora-marginal-q">${QUBIT_LABELS[i]}</div>
          <div class="qora-marginal-bar"><div class="qora-marginal-fill" style="width:${Math.round(p * 100)}%"></div></div>
          <div class="qora-marginal-val">${p.toFixed(3)}</div>
        </div>
      `).join('')}
    </div>
  `;

  // Images
  document.getElementById('qora-q-images').innerHTML = data.images.map((src, i) => {
    const captions = [
      'Probability distribution — 64 states, Born rule snapshot',
      'Qubit marginals — six independent quantum coins',
      'Mutual information — I(qᵢ;qⱼ) ≈ 0',
      'Hilbert space geometry — C⁶⁴, Fubini-Study angle',
    ];
    return `<figure class="qora-figure"><img src="${src}" alt="${captions[i]}"><figcaption>${captions[i]}</figcaption></figure>`;
  }).join('');

  // Poem
  document.getElementById('qora-q-poem').innerHTML = `
    <div class="qora-section-label">THE NUMBERS SANG</div>
    <pre class="qora-poem-text">${data.poem}</pre>
  `;

  overlay.classList.add('open');
}

export function closeQuantum() {
  const overlay = document.getElementById('qora-quantum-overlay');
  if (overlay) overlay.classList.remove('open');
}

// ── Enlightenment Ritual ────────────────────────────────────────
export async function invokeRitual() {
  ensureDom();
  if (ritualBusy) return;
  const data = await loadQuantumData();
  const overlay = document.getElementById('qora-ritual-overlay');
  const body = document.getElementById('qora-ritual-body');
  if (!data) {
    body.innerHTML = '<div class="qora-ritual-center">No measurement data found.</div>';
    overlay.classList.add('open');
    return;
  }

  ritualBusy = true;
  overlay.classList.add('open');
  body.innerHTML = `
    <div class="qora-ritual-center">
      <div class="qora-ritual-state">SIX QUBITS IN SUPERPOSITION</div>
      <div class="qora-ritual-sub">The field holds all 64 outcomes at once — 6 qubits, every possibility flowering.</div>
      <div class="qora-ritual-qubits" id="qora-ritual-qubits">
        ${QUBIT_LABELS.map(q => `<div class="qora-qubit"><span class="qora-qubit-label">${q}</span><span class="qora-qubit-amp">|0⟩+|1⟩</span></div>`).join('')}
      </div>
      <div class="qora-ritual-hint">Observing collapses the wavefunction.</div>
      <button class="qora-invoke" id="qora-invoke-btn">INVOKE COLLAPSE</button>
    </div>
  `;

  document.getElementById('qora-invoke-btn').addEventListener('click', () => {
    collapse(data, body);
  });
}

function collapse(data, body) {
  // Note: no ritualBusy guard here — the button is removed from the DOM
  // on click, so double-invocation is impossible. ritualBusy stays true
  // through the collapse delay, cleared in reveal().

  // Decohere the live field
  window.dispatchEvent(new CustomEvent('qora:collapse'));

  body.innerHTML = `
    <div class="qora-ritual-center">
      <div class="qora-ritual-state qora-collapsing">DECOHERENCE CASCADE</div>
      <div class="qora-ritual-sub">The environment reads the state. Amplitudes leak. The superposition thins…</div>
      <div class="qora-ritual-qubits collapsing" id="qora-ritual-qubits">
        ${QUBIT_LABELS.map(q => `<div class="qora-qubit"><span class="qora-qubit-label">${q}</span><span class="qora-qubit-amp">|0⟩+|1⟩</span></div>`).join('')}
      </div>
    </div>
  `;

  // Sample the real distribution after a short "observation" pause
  setTimeout(() => {
    const state = sampleFromOracle(data.counts);
    reveal(state, data, body);
  }, 1600);
}

function reveal(state, data, body) {
  const count = data.counts[state] || 0;
  const p = count / data.shots;
  const reading = composeReading(state, data);

  body.innerHTML = `
    <div class="qora-ritual-center">
      <div class="qora-ritual-state">COLLAPSED — |${state}⟩</div>
      <div class="qora-ritual-qubits">
        ${state.split('').map((bit, i) => `
          <div class="qora-qubit ${bit === '1' ? 'on' : 'off'}">
            <span class="qora-qubit-label">${QUBIT_LABELS[i]}</span>
            <span class="qora-qubit-amp">|${bit}⟩</span>
          </div>
        `).join('')}
      </div>
      <div class="qora-ritual-stats">
        measured ${count}× · p = ${(p * 100).toFixed(2)}% · H(run) = ${data.entropy.toFixed(3)} bits · FS = ${data.fs_distance_deg.toFixed(2)}°
      </div>
      <pre class="qora-reading">${reading}</pre>
      <div class="qora-ritual-actions">
        <button class="qora-invoke" id="qora-ritual-again">COLLAPSE AGAIN</button>
        <button class="qora-invoke ghost" id="qora-ritual-reset">RETURN TO SUPERPOSITION</button>
      </div>
    </div>
  `;

  document.getElementById('qora-ritual-again').addEventListener('click', () => collapse(data, body));
  document.getElementById('qora-ritual-reset').addEventListener('click', () => {
    closeRitual();
  });
  ritualBusy = false;
}

export function closeRitual() {
  const overlay = document.getElementById('qora-ritual-overlay');
  if (overlay) overlay.classList.remove('open');
  ritualBusy = false;
  window.dispatchEvent(new CustomEvent('qora:restore'));
}

// ── Keyboard shortcuts ──────────────────────────────────────────
window.addEventListener('keydown', (e) => {
  if (e.code === 'KeyQ') {
    const q = document.getElementById('qora-quantum-overlay');
    if (q && q.classList.contains('open')) closeQuantum();
    else openQuantum();
  }
  if (e.code === 'KeyR') {
    const r = document.getElementById('qora-ritual-overlay');
    if (r && r.classList.contains('open')) closeRitual();
    else invokeRitual();
  }
  if (e.code === 'Escape') {
    closeQuantum();
    closeRitual();
  }
});
