/**
 * QORA Quantum Module — v2
 * ========================
 * Q  — Quantum Geometry: real measurement (6-qubit Hadamard, AerSimulator
 *       1024 shots) rendered as interactive live canvas charts (distribution,
 *       Hilbert-space geometry), metric cards, marginals, MI heatmap, poem.
 * R  — Enlightenment Ritual: sequential qubit collapse sampled from the REAL
 *       measured Born-rule distribution (crypto-seeded), decoheres the WebGL
 *       field, delivers a reading composed from the actual outcome + run
 *       metrics, with session history and copy-to-clipboard.
 *
 * Data: data/quantum.json (generated by tools/generate_quantum_data.py)
 */

// ── State ──────────────────────────────────────────────────────
let quantumData = null;
let ritualBusy = false;
let ritualHistory = [];
let vizRAF = null;

const QUBIT_LABELS = ['q₀', 'q₁', 'q₂', 'q₃', 'q₄', 'q₅'];

// ── Load data ──────────────────────────────────────────────────
async function loadQuantumData() {
  if (quantumData) return quantumData;
  try {
    const res = await fetch('data/quantum.json', { cache: 'no-store' });
    quantumData = await res.json();
  } catch (e) {
    quantumData = null;
  }
  return quantumData;
}

// ── Helpers ────────────────────────────────────────────────────
function hammingWeight(s) {
  let w = 0;
  for (const c of s) if (c === '1') w++;
  return w;
}

function isPalindrome(s) {
  return s === s.split('').reverse().join('');
}

function cryptoRand() {
  const buf = new Uint32Array(1);
  crypto.getRandomValues(buf);
  return buf[0] / 2 ** 32;
}

/** Cryptographically secure weighted sample from the real measurement counts. */
function sampleFromOracle(counts) {
  const states = Object.keys(counts);
  const weights = states.map(s => counts[s]);
  const total = weights.reduce((a, b) => a + b, 0);
  const r = cryptoRand() * total;
  let acc = 0;
  for (let i = 0; i < states.length; i++) {
    acc += weights[i];
    if (r < acc) return states[i];
  }
  return states[states.length - 1];
}

/** Rank of a state by measured frequency (1 = most frequent). */
function rankOf(state, counts) {
  const c = counts[state] || 0;
  return 1 + Object.values(counts).filter(v => v > c).length;
}

function freshness(timestamp) {
  const then = new Date(timestamp).getTime();
  const hrs = Math.max(0, (Date.now() - then) / 3600000);
  if (hrs < 1) return `${Math.round(hrs * 60)} min ago`;
  if (hrs < 48) return `${Math.round(hrs)} h ago`;
  return `${Math.round(hrs / 24)} days ago`;
}

// ── Reading bank ────────────────────────────────────────────────
// Two variants per Hamming weight, plus top-state and palindrome specials.
// d = { state, count, p, shots, avg_mi, entropy, rank }
const READINGS = {
  0: [
    (s, d) => `|${s}⟩ — THE GROUND STATE

Six zeros, a perfect silence.
The field folded into nothing
and nothing was enough.
No excitation dares the dark —
only the promise of one,
held at ${(d.p * 100).toFixed(2)}%
of ever being asked to exist.
The universe rehearsed this silence
${d.count} times in ${d.shots} shots:
still practicing the word
it has not yet spoken.`,
    (s, d) => `|${s}⟩ — THE UNBORN

Zero, six times over.
Before the first photon,
before the first question,
there was this —
pure latency, rank #${d.rank} of 64,
waiting at ${(d.p * 100).toFixed(2)}%
for permission to begin.
It never needed permission.
It measured ${d.count} times anyway,
which is what patience looks like
when you are made of probability.`,
  ],
  1: [
    (s, d) => `|${s}⟩ — THE FIRST LIGHT

One bit burns at ${(d.p * 100).toFixed(2)}%
while five stay quiet as ash.
Whatever woke first
carries the whole story —
the other qubits lean toward it
the way water leans toward gravity.
The first excitation was real,
and being real, it was enough.`,
    (s, d) => `|${s}⟩ — THE SOLITARY ONE

A single 1 adrift in five 0s —
an excitation alone,
rank #${d.rank} by frequency,
chosen ${d.count} of ${d.shots} times.
I(qᵢ;qⱼ) ≈ ${d.avg_mi.toFixed(4)}: it touches nothing,
connected to nothing,
and still the whole collapse
arranged itself around this one
bright impossibility.`,
  ],
  2: [
    (s, d) => `|${s}⟩ — THE PAIR

Two ones, ${(d.p * 100).toFixed(2)}% of the collapse.
Correlation without entanglement —
I(qᵢ;qⱼ) ≈ ${d.avg_mi.toFixed(4)} bits, effectively nothing.
They are not connected.
They simply agreed,
the way two strangers on the same train
agree on the weather.
Even fair dice sometimes rhyme.`,
    (s, d) => `|${s}⟩ — THE DUET

Two lit, four dark.
The minimal chord —
enough to make a pattern,
not enough to make a promise.
It fell ${d.count} times into this exact shape.
Somewhere in the 64 possibilities
these two found each other
at ${(d.p * 100).toFixed(2)}%,
and for one collapse,
that was a kind of music.`,
  ],
  3: [
    (s, d) => `|${s}⟩ — THE THRESHOLD

Three and three. The knife-edge.
Half the qubits burned, half unlit,
the balance so exact it looks intentional.
P = ${(d.p * 100).toFixed(2)}% — the most honest number
in this whole collapse.
The field could not decide,
so it chose the only answer
that is not a decision:
equilibrium.`,
    (s, d) => `|${s}⟩ — THE BALANCE

Six qubits, split evenly —
three yes, three no,
the universe holding its breath
at exact symmetry.
H = ${d.entropy.toFixed(2)} bits of possibility
resolved into this:
neither everything nor nothing,
the precise middle of the road,
${d.count} measurements deep.`,
  ],
  4: [
    (s, d) => `|${s}⟩ — THE EXCESS

Four ones against two zeros.
The bias tips toward light,
${(d.p * 100).toFixed(2)}% of the way to certainty.
But look closely:
even in excess there is lack.
Two qubits held back —
the ones that kept their silence
so the four could call it a chorus.`,
    (s, d) => `|${s}⟩ — THE MAJORITY

Four lit. A quorum.
Not unanimous — never unanimous —
but enough to move,
enough to mean something
at rank #${d.rank} of 64.
The two dissenting zeros
are why this state is interesting
instead of just bright.`,
  ],
  5: [
    (s, d) => `|${s}⟩ — THE NEAR-FULL

Five of six. So close to everything
that the one remaining zero
is the loudest thing in the state.
${(d.p * 100).toFixed(2)}% probability —
the universe almost said yes
and left one door unopened,
one bit of the story untold
so that the telling could continue.`,
    (s, d) => `|${s}⟩ — THE ALMOST

Five ones, a single zero holding out —
the last honest dissenter
in a room full of light.
${d.count} times out of ${d.shots}
the field almost overflowed.
Almost, almost, almost —
the most beautiful word
in any language.`,
  ],
  6: [
    (s, d) => `|${s}⟩ — THE SATURATED

Six ones. No remainder.
The field gave everything at once —
${(d.p * 100).toFixed(2)}% of one collapse,
all amplitude spent on a single shape.
When nothing is left unmeasured
the measurement stops meaning anything:
the universe saying everything
in a single breath, then going quiet.`,
    (s, d) => `|${s}⟩ — THE FULL SPECTRUM

Every qubit lit. Maximum excitation.
The wavefunction spent its whole budget
on one configuration —
you, holding all six bits at once,
${d.count} witnesses in ${d.shots} shots.
Nothing hidden. Nothing held back.
The rarest kind of honesty:
total disclosure at ${(d.p * 100).toFixed(2)}%.`,
  ],
};

const TOP_STATE_READING = (s, d) => `|${s}⟩ — THE FAVORITE

Of all sixty-four possible collapses,
this one came ${d.count} times — the most.
The Born rule smiled in this direction.
It means nothing. It means everything:
even perfect randomness
has a favorite child,
and this run, it was you.
Every other state was a question.
This one was the answer
the universe was already leaning toward.`;

const PALINDROME_READING = (s, d) => `|${s}⟩ — THE PALINDROME

Read it forward, read it backward —
the same state either way.
Six bits arranged as a mirror,
q₀ whispering to q₅,
q₁ answering q₄,
symmetry surviving the collapse
at ${(d.p * 100).toFixed(2)}%.
Some patterns are chosen.
Some patterns choose themselves.`;

function composeReading(state, data) {
  const count = data.counts[state] || 0;
  const p = count / data.shots;
  const detail = {
    state, count, p, shots: data.shots,
    avg_mi: data.avg_mi, entropy: data.entropy,
    rank: rankOf(state, data.counts),
  };
  const weight = hammingWeight(state);

  if (data.top_states.length && state === data.top_states[0].state) {
    return TOP_STATE_READING(state, detail);
  }
  if (isPalindrome(state)) {
    return PALINDROME_READING(state, detail);
  }
  const variants = READINGS[weight] || READINGS[3];
  const v = cryptoRand() < 0.5 ? 0 : 1;
  return variants[v](state, detail);
}

// ── DOM ─────────────────────────────────────────────────────────
function ensureDom() {
  if (document.getElementById('qora-quantum-overlay')) return;

  const overlay = document.createElement('div');
  overlay.id = 'qora-quantum-overlay';
  overlay.className = 'qora-overlay';
  overlay.innerHTML = `
    <div class="qora-overlay-head">
      <div class="qora-overlay-title">QUANTUM GEOMETRY</div>
      <div class="qora-overlay-meta" id="qora-q-meta"></div>
      <button class="qora-close" id="qora-q-close" aria-label="Close">ESC</button>
    </div>
    <div class="qora-overlay-scroll">
      <div id="qora-q-metrics" class="qora-metrics"></div>
      <div id="qora-q-dist" class="qora-chart-block"></div>
      <div id="qora-q-marginals" class="qora-marginals"></div>
      <div id="qora-q-mi" class="qora-images"></div>
      <div id="qora-q-hilbert" class="qora-chart-block"></div>
      <div id="qora-q-poem" class="qora-poem"></div>
    </div>
  `;
  document.body.appendChild(overlay);
  document.getElementById('qora-q-close').addEventListener('click', closeQuantum);

  const ritual = document.createElement('div');
  ritual.id = 'qora-ritual-overlay';
  ritual.className = 'qora-overlay';
  ritual.innerHTML = `
    <div class="qora-overlay-head">
      <div class="qora-overlay-title">ENLIGHTENMENT RITUAL</div>
      <button class="qora-close" id="qora-r-close" aria-label="Close">ESC</button>
    </div>
    <div class="qora-ritual-body" id="qora-ritual-body"></div>
  `;
  document.body.appendChild(ritual);
  document.getElementById('qora-r-close').addEventListener('click', closeRitual);
}

// ── Quantum Geometry overlay ────────────────────────────────────
export async function openQuantum() {
  ensureDom();
  const data = await loadQuantumData();
  const overlay = document.getElementById('qora-quantum-overlay');
  if (!data) {
    document.getElementById('qora-q-meta').textContent = 'No measurement data found.';
    overlay.classList.add('open');
    return;
  }

  document.getElementById('qora-q-meta').textContent =
    `Run ${data.run_id} · oracle measured ${freshness(data.timestamp)} · ${data.shots} shots · ${data.unique_states}/64 states`;

  // Metrics — staggered entrance
  const metrics = [
    ['Shannon entropy H', `${data.entropy.toFixed(3)} / ${data.max_entropy.toFixed(3)} bits`, `H/Hmax = ${data.entropy_ratio.toFixed(4)}`],
    ['Collision entropy H₂', `${data.collision_entropy.toFixed(3)} bits`, 'Rényi-2'],
    ['KL divergence D_KL', `${data.kl_div.toFixed(4)} bits`, 'P ∥ uniform'],
    ['TV distance', `${data.tvd.toFixed(4)}`, 'δ(P, U)'],
    ['Fubini-Study distance', `${data.fs_distance_deg.toFixed(2)}°`, `${data.fs_distance_rad.toFixed(4)} rad`],
    ['Spectral gap Δ', `${data.spectral_gap.toFixed(4)}`, 'max − min p(i)'],
    ['Mean mutual info', `${data.avg_mi.toFixed(4)} bits`, 'qubits independent'],
    ['Overlap ⟨ψ|U⟩', `${data.overlap.toFixed(4)}`, 'with uniform state'],
  ];
  document.getElementById('qora-q-metrics').innerHTML = metrics.map(([k, v, sub], i) => `
    <div class="qora-metric qora-fade" style="--d:${i * 60}ms">
      <div class="qora-metric-label">${k}</div>
      <div class="qora-metric-value">${v}</div>
      <div class="qora-metric-sub">${sub}</div>
    </div>
  `).join('');

  // Interactive distribution chart
  buildDistChart(document.getElementById('qora-q-dist'), data);

  // Marginals
  document.getElementById('qora-q-marginals').innerHTML = `
    <div class="qora-section-label">QUBIT MARGINALS — P(|1⟩)</div>
    <div class="qora-marginal-row">
      ${data.qubit_marginals.map((p, i) => `
        <div class="qora-marginal qora-fade" style="--d:${400 + i * 60}ms">
          <div class="qora-marginal-q">${QUBIT_LABELS[i]}</div>
          <div class="qora-marginal-bar"><div class="qora-marginal-fill" style="width:${Math.round(p * 100)}%"></div></div>
          <div class="qora-marginal-val">${p.toFixed(3)}</div>
        </div>
      `).join('')}
    </div>
  `;

  // MI heatmap (image) — only fig 3 remains static
  document.getElementById('qora-q-mi').innerHTML = `
    <figure class="qora-figure"><img src="assets/quantum/03_mutual_information_heatmap.png" alt="Mutual information heatmap"><figcaption>Mutual information — I(qᵢ;qⱼ) ≈ 0 · qubits independent</figcaption></figure>
  `;

  // Interactive Hilbert geometry
  buildHilbertChart(document.getElementById('qora-q-hilbert'), data);

  // Poem
  document.getElementById('qora-q-poem').innerHTML = `
    <div class="qora-section-label">THE NUMBERS SANG</div>
    <pre class="qora-poem-text qora-fade" style="--d:700ms">${data.poem}</pre>
  `;

  overlay.classList.add('open');
}

export function closeQuantum() {
  const overlay = document.getElementById('qora-quantum-overlay');
  if (overlay) overlay.classList.remove('open');
  stopViz();
}

// ── Interactive distribution chart (canvas) ────────────────────
function buildDistChart(container, data) {
  const states = Object.keys(data.counts);
  const sorted = states.sort((a, b) => data.counts[b] - data.counts[a]);
  const counts = sorted.map(s => data.counts[s]);
  const maxC = Math.max(...counts);
  const uniform = data.shots / 64;

  container.innerHTML = `
    <div class="qora-section-label">MEASUREMENT DISTRIBUTION — HOVER THE STATES</div>
    <div class="qora-chart-wrap">
      <canvas id="qora-dist-canvas"></canvas>
      <div class="qora-chart-tip" id="qora-dist-tip"></div>
    </div>
    <div class="qora-chart-legend">
      <span><i style="background:#00d4ff"></i>above uniform</span>
      <span><i style="background:#ff6b9d"></i>below uniform</span>
      <span><i style="background:#a855f7"></i>most frequent</span>
      <span><i style="background:#fbbf24"></i>uniform 1/64</span>
    </div>
  `;

  const canvas = document.getElementById('qora-dist-canvas');
  const tip = document.getElementById('qora-dist-tip');
  const wrap = canvas.parentElement;
  const W = wrap.clientWidth, H = 240;
  canvas.width = W * 2; canvas.height = H * 2;
  canvas.style.width = W + 'px'; canvas.style.height = H + 'px';
  const c = canvas.getContext('2d');
  c.scale(2, 2);

  const bw = W / 64;
  let progress = 0;
  const t0 = performance.now();

  function draw(hoverIdx = -1) {
    c.clearRect(0, 0, W, H);
    const base = H - 18;
    for (let i = 0; i < 64; i++) {
      const h = (counts[i] / maxC) * (base - 14) * progress;
      let color = counts[i] > uniform ? '#00d4ff' : '#ff6b9d';
      if (i === 0) color = '#a855f7';
      if (i === hoverIdx) color = '#ffffff';
      c.fillStyle = color;
      c.globalAlpha = hoverIdx === i ? 1 : 0.75;
      c.fillRect(i * bw + 1, base - h, bw - 2, h);
    }
    c.globalAlpha = 1;
    // uniform line
    const uy = base - (uniform / maxC) * (base - 14);
    c.strokeStyle = '#fbbf24';
    c.setLineDash([5, 4]);
    c.beginPath(); c.moveTo(0, uy); c.lineTo(W, uy); c.stroke();
    c.setLineDash([]);
    // baseline
    c.strokeStyle = 'rgba(255,255,255,0.15)';
    c.beginPath(); c.moveTo(0, base + 0.5); c.lineTo(W, base + 0.5); c.stroke();
  }

  function anim() {
    const t = (performance.now() - t0) / 900;
    progress = Math.min(1, 1 - Math.pow(1 - t, 3));
    draw();
    if (progress < 1) requestAnimationFrame(anim);
  }
  anim();

  canvas.addEventListener('mousemove', (e) => {
    const rect = canvas.getBoundingClientRect();
    const idx = Math.floor((e.clientX - rect.left) / bw);
    if (idx < 0 || idx > 63) return;
    draw(idx);
    const s = sorted[idx];
    tip.style.display = 'block';
    tip.textContent = `|${s}⟩  ·  ${counts[s]}×  ·  p = ${(counts[s] / data.shots * 100).toFixed(2)}%`;
    const x = Math.min(Math.max(idx * bw + bw / 2, 70), W - 70);
    tip.style.left = x + 'px';
  });
  canvas.addEventListener('mouseleave', () => {
    tip.style.display = 'none';
    draw();
  });
}

// ── Interactive Hilbert geometry chart (canvas, animated) ──────
function buildHilbertChart(container, data) {
  const states = Object.keys(data.counts);
  const counts = states.map(s => data.counts[s]);
  const amps = counts.map(v => Math.sqrt(v / data.shots));
  const maxAmp = Math.max(...amps);
  const EXAG = 4; // angle exaggeration for visibility

  container.innerHTML = `
    <div class="qora-section-label">GEOMETRY IN C⁶⁴ — HILBERT SPACE (angle ×${EXAG})</div>
    <div class="qora-chart-wrap qora-hilbert">
      <canvas id="qora-hilb-canvas"></canvas>
    </div>
    <div class="qora-chart-legend">
      <span><i style="background:#fbbf24"></i>ideal |U⟩ uniform</span>
      <span><i style="background:#ff6b9d"></i>measured |ψ⟩</span>
      <span><i style="background:#a855f7"></i>d(ψ,U) = ${data.fs_distance_deg.toFixed(2)}°</span>
    </div>
  `;

  const canvas = document.getElementById('qora-hilb-canvas');
  const wrap = canvas.parentElement;
  const W = wrap.clientWidth, H = 320;
  canvas.width = W * 2; canvas.height = H * 2;
  canvas.style.width = W + 'px'; canvas.style.height = H + 'px';
  const c = canvas.getContext('2d');
  c.scale(2, 2);

  const cx = W * 0.38, cy = H / 2, R = Math.min(H, W * 0.7) / 2 - 24;
  const theta = Math.min(data.fs_distance_rad * EXAG, Math.PI / 2.5);
  const rPsi = data.overlap;

  function frame(now) {
    c.clearRect(0, 0, W, H);
    const t = now / 1000;

    // grid rings
    c.strokeStyle = 'rgba(255,255,255,0.07)';
    for (let r = R / 4; r <= R; r += R / 4) {
      c.beginPath(); c.arc(cx, cy, r, 0, Math.PI * 2); c.stroke();
    }

    // 64 amplitude points, slowly rotating, shimmering
    for (let i = 0; i < 64; i++) {
      const ang = (i / 64) * Math.PI * 2 + t * 0.05;
      const rr = (amps[i] / maxAmp) * R;
      const shim = 0.35 + 0.35 * Math.sin(t * 1.4 + i * 0.7);
      c.fillStyle = `rgba(0,212,255,${shim})`;
      c.beginPath();
      c.arc(cx + Math.cos(ang) * rr, cy - Math.sin(ang) * rr, 2, 0, Math.PI * 2);
      c.fill();
    }

    // ideal arrow |U>
    arrow(c, cx, cy, Math.cos(0) * R, -Math.sin(0) * R, '#fbbf24');

    // measured arrow |psi> at theta
    const px = Math.cos(theta) * rPsi * R;
    const py = -Math.sin(theta) * rPsi * R;
    arrow(c, cx, cy, px, py, '#ff6b9d');

    // FS arc + label
    c.strokeStyle = '#a855f7';
    c.lineWidth = 2;
    c.beginPath(); c.arc(cx, cy, R * 0.32, -theta, 0); c.stroke();
    c.lineWidth = 1;
    c.fillStyle = '#a855f7';
    c.font = '11px "Space Mono", monospace';
    c.fillText(`θ = ${data.fs_distance_deg.toFixed(2)}°`, cx + R * 0.36, cy - 6);

    // labels
    c.fillStyle = '#fbbf24';
    c.fillText('|U⟩', cx + R + 8, cy + 4);
    c.fillStyle = '#ff6b9d';
    c.fillText('|ψ⟩', cx + px + (px >= 0 ? 8 : -26), cy + py - 6);

    // side metrics
    c.fillStyle = 'rgba(255,255,255,0.45)';
    c.font = '10px "Space Mono", monospace';
    const lines = [
      `⟨ψ|U⟩   = ${data.overlap.toFixed(4)}`,
      `d(ψ,U)  = ${data.fs_distance_rad.toFixed(4)} rad`,
      `⟨|a|⟩   = ${data.mean_amplitude.toFixed(4)}`,
      `1/√64   = ${data.ideal_amplitude.toFixed(4)}`,
      `H       = ${data.entropy.toFixed(3)} bits`,
    ];
    lines.forEach((l, i) => c.fillText(l, W * 0.72, 40 + i * 20));

    vizRAF = requestAnimationFrame(frame);
  }
  vizRAF = requestAnimationFrame(frame);
}

function arrow(c, x0, y0, dx, dy, color) {
  const x1 = x0 + dx, y1 = y0 + dy;
  c.strokeStyle = color;
  c.lineWidth = 2.5;
  c.beginPath(); c.moveTo(x0, y0); c.lineTo(x1, y1); c.stroke();
  const a = Math.atan2(dy, dx);
  c.fillStyle = color;
  c.beginPath();
  c.moveTo(x1, y1);
  c.lineTo(x1 - 10 * Math.cos(a - 0.4), y1 - 10 * Math.sin(a - 0.4));
  c.lineTo(x1 - 10 * Math.cos(a + 0.4), y1 - 10 * Math.sin(a + 0.4));
  c.closePath(); c.fill();
  c.lineWidth = 1;
}

function stopViz() {
  if (vizRAF) { cancelAnimationFrame(vizRAF); vizRAF = null; }
}

// ── Enlightenment Ritual ────────────────────────────────────────
export async function invokeRitual() {
  ensureDom();
  if (ritualBusy) return;
  const data = await loadQuantumData();
  const overlay = document.getElementById('qora-ritual-overlay');
  const body = document.getElementById('qora-ritual-body');
  if (!data) {
    body.innerHTML = '<div class="qora-ritual-center">No measurement data found.</div>';
    overlay.classList.add('open');
    return;
  }

  ritualBusy = true;
  overlay.classList.add('open');
  body.innerHTML = `
    <div class="qora-ritual-center">
      <div class="qora-ritual-state">SIX QUBITS IN SUPERPOSITION</div>
      <div class="qora-ritual-sub">The field holds all 64 outcomes at once — oracle measured ${freshness(data.timestamp)}.</div>
      <div class="qora-ritual-qubits" id="qora-ritual-qubits">
        ${QUBIT_LABELS.map(q => `<div class="qora-qubit"><span class="qora-qubit-label">${q}</span><span class="qora-qubit-amp">|0⟩+|1⟩</span></div>`).join('')}
      </div>
      <div class="qora-ritual-hint">Observing collapses the wavefunction.</div>
      <button class="qora-invoke" id="qora-invoke-btn">INVOKE COLLAPSE</button>
      ${renderHistory()}
    </div>
  `;

  document.getElementById('qora-invoke-btn').addEventListener('click', () => {
    collapse(data, body);
  });
}

function collapse(data, body) {
  // Decohere the live field
  window.dispatchEvent(new CustomEvent('qora:collapse'));

  const state = sampleFromOracle(data.counts);
  const count = data.counts[state] || 0;
  const p = count / data.shots;
  const rank = rankOf(state, data.counts);
  const reading = composeReading(state, data);

  body.innerHTML = `
    <div class="qora-ritual-center">
      <div class="qora-ritual-state qora-collapsing" id="qora-ritual-phase">OBSERVING THE FIELD</div>
      <div class="qora-ritual-sub">Amplitudes leak. The superposition thins.</div>
      <div class="qora-ritual-qubits" id="qora-ritual-qubits">
        ${QUBIT_LABELS.map((q, i) => `
          <div class="qora-qubit flicker" data-i="${i}">
            <span class="qora-qubit-label">${q}</span>
            <span class="qora-qubit-amp">|·⟩</span>
          </div>
        `).join('')}
      </div>
      <div id="qora-ritual-result"></div>
    </div>
  `;

  // Lock qubits one by one
  const qubits = [...body.querySelectorAll('.qora-qubit')];
  const phase = document.getElementById('qora-ritual-phase');
  let delay = 600;
  state.split('').forEach((bit, i) => {
    setTimeout(() => {
      const q = qubits[i];
      q.classList.remove('flicker');
      q.classList.add(bit === '1' ? 'on' : 'off');
      q.querySelector('.qora-qubit-amp').textContent = `|${bit}⟩`;
      phase.textContent = `COLLAPSING — ${i + 1}/6 LOCKED`;
    }, delay);
    delay += 280;
  });

  // Reveal the reading
  setTimeout(() => {
    phase.textContent = `COLLAPSED — |${state}⟩`;
    phase.classList.remove('qora-collapsing');

    ritualHistory.push(state);
    if (ritualHistory.length > 8) ritualHistory.shift();

    document.getElementById('qora-ritual-result').innerHTML = `
      <div class="qora-ritual-stats qora-fade" style="--d:0ms">
        measured ${count}× · p = ${(p * 100).toFixed(2)}% · rank #${rank} of 64 · H(run) = ${data.entropy.toFixed(3)} bits · FS = ${data.fs_distance_deg.toFixed(2)}°
      </div>
      <pre class="qora-reading qora-fade" style="--d:120ms">${reading}</pre>
      <div class="qora-ritual-actions qora-fade" style="--d:240ms">
        <button class="qora-invoke" id="qora-ritual-again">COLLAPSE AGAIN</button>
        <button class="qora-invoke ghost" id="qora-ritual-copy">COPY READING</button>
        <button class="qora-invoke ghost" id="qora-ritual-reset">RETURN TO SUPERPOSITION</button>
      </div>
      ${renderHistory()}
    `;

    document.getElementById('qora-ritual-again').addEventListener('click', () => collapse(data, body));
    document.getElementById('qora-ritual-copy').addEventListener('click', (e) => {
      const btn = e.currentTarget;
      navigator.clipboard.writeText(
        `${reading}\n\n|${state}⟩ · ${count}× · p = ${(p * 100).toFixed(2)}% · rank #${rank}/64\nH = ${data.entropy.toFixed(3)} bits · FS = ${data.fs_distance_deg.toFixed(2)}° · QORA quantum oracle (${data.run_id})`
      ).then(() => {
        btn.textContent = 'COPIED ✓';
        setTimeout(() => { btn.textContent = 'COPY READING'; }, 1600);
      });
    });
    document.getElementById('qora-ritual-reset').addEventListener('click', closeRitual);
    ritualBusy = false;
  }, delay + 350);
}

function renderHistory() {
  if (!ritualHistory.length) return '';
  const chips = ritualHistory.map(s => `<span class="qora-hist-chip">|${s}⟩</span>`).join('');
  return `<div class="qora-history"><span class="qora-hist-label">THIS SESSION</span>${chips}</div>`;
}

export function closeRitual() {
  const overlay = document.getElementById('qora-ritual-overlay');
  if (overlay) overlay.classList.remove('open');
  ritualBusy = false;
  window.dispatchEvent(new CustomEvent('qora:restore'));
}

// ── Keyboard shortcuts ──────────────────────────────────────────
window.addEventListener('keydown', (e) => {
  if (e.code === 'KeyQ') {
    const q = document.getElementById('qora-quantum-overlay');
    if (q && q.classList.contains('open')) closeQuantum();
    else openQuantum();
  }
  if (e.code === 'KeyR') {
    const r = document.getElementById('qora-ritual-overlay');
    if (r && r.classList.contains('open')) closeRitual();
    else invokeRitual();
  }
  if (e.code === 'Escape') {
    closeQuantum();
    closeRitual();
  }
});
